management:
  endpoints:
    web:
      exposure:
        include: '*'
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password: thiva456
    driver-class-name: com.mysql.cj.jdbc.Driver     

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
      ddl-auto: create-drop

server:
  port: 1212

              